name: whatsapp_share_plus
description: Simple way to share message, links or files from your flutter app to specific contact in whatsapp
version: 2.1.0
homepage: https://github.com/chandrabezzo/whatsapp_share_plus
issue_tracker: https://github.com/chandrabezzo/whatsapp_share_plus/issues

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.solusibejo.whatsapp_share_plus
        pluginClass: WhatsappShare
      ios:
        pluginClass: WhatsappShare

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"